name: automate workflow

on: 
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

  
